version: "3.7"

services:
  web:
    build: ./src
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 everest.wsgi:application
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1