# Generated by Django 3.1.4 on 2020-12-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20201208_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='proximity',
        ),
    ]
