# Generated by Django 3.1.4 on 2020-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20201208_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='x_coordinate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='y_coordinate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='z_coordinate',
            field=models.FloatField(default=0),
        ),
    ]
