# Generated by Django 3.1.4 on 2020-12-09 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20201209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
