# Generated by Django 3.1.4 on 2020-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
        migrations.AddField(
            model_name='sensor',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='identifier',
            field=models.CharField(db_index=True, default='unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
