# Generated by Django 3.1.4 on 2020-12-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20201208_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='identifier',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
