# Generated by Django 3.1.4 on 2020-12-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_proximitydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensor'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name_plural': 'Sensor Data'},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='identifier',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.sensor'),
        ),
    ]
