# Generated by Django 3.1.4 on 2020-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20201208_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proximitydata',
            options={'verbose_name_plural': 'Proximity Data'},
        ),
        migrations.RemoveField(
            model_name='proximitydata',
            name='source',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
